# embed_metal_sources.cmake — turns .metal files into a header with the source
# embedded as constexpr C strings, so metal_aggregator.mm and metal_groupby.mm
# can pass them to MTLDevice newLibraryWithSource at runtime.
#
# Why not pre-compile to .metallib?
#   - Avoids xcrun toolchain complexity in CMake.
#   - Source is small (~5 KB total) — runtime compile takes <10 ms.
#   - The .metal files stay readable as canonical source-of-truth.

function(gpudb_embed_metal_sources OUT_HEADER)
    set(_pairs ${ARGN})  # alternating: VAR_NAME source.metal VAR_NAME source.metal ...
    set(_content "// Auto-generated by cmake/embed_metal_sources.cmake — DO NOT EDIT.\n")
    set(_content "${_content}#pragma once\nnamespace gpudb::metal {\n")

    list(LENGTH _pairs _n)
    math(EXPR _last "${_n} - 1")
    set(_i 0)
    while(_i LESS _n)
        list(GET _pairs ${_i} _var)
        math(EXPR _j "${_i} + 1")
        list(GET _pairs ${_j} _src)
        if(NOT EXISTS "${_src}")
            message(FATAL_ERROR "gpudb_embed_metal_sources: missing ${_src}")
        endif()
        file(READ "${_src}" _src_text)
        # Use a delimiter that won't appear in MSL source.
        set(_content "${_content}\ninline constexpr const char ${_var}[] = R\"GPUDBMETAL(\n${_src_text})GPUDBMETAL\";\n")
        math(EXPR _i "${_i} + 2")
    endwhile()

    set(_content "${_content}\n} // namespace gpudb::metal\n")
    file(WRITE "${OUT_HEADER}" "${_content}")
endfunction()
